name: pcdiff-ldct
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - numpy
  - scipy
  - tqdm
  - pyyaml
  - omegaconf
  - tensorboard
  - scikit-image
  - h5py
  - pydicom
  - opencv
  - pip
  - pip:
      - torch-radon>=2.0.0
